name: docker-ci.yml

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Test container
        run: |
          # Run the container in detached mode
          docker compose up -d
          
          # Wait for a few seconds to ensure the container is up and running
          sleep 90
          
          # Test the application endpoint
          curl -f http://localhost:3000 || exit 1
          
          # Stop and remove the container
          docker compose down
